adminProduits:
    path:     /
    defaults: { _controller: "EcommerceBundle:Produits:index" }

adminProduits_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:Produits:show" }

adminProduits_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:Produits:new" }

adminProduits_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:Produits:create" }
    methods:  POST

adminProduits_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:Produits:edit" }

adminProduits_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:Produits:update" }
    methods:  [POST, PUT]

adminProduits_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:Produits:delete" }
    methods:  [POST, DELETE]
